### PR TITLE
Create a 'none' theme.

### PR DESCRIPTION
**Pull request by MattMSumner**
Why:

* I would like to forgo the jquery-ui css and instead style the
components myself.

This PR:

* Allows the user to set the theme to none.

### CODE REVIEW

**Comment by MattMSumner** [comment]
@Gaurav0 nice addon. Let me know if this PR seems reasonable.

**Comment by MattMSumner** [comment]
Sweet! Would you mind publishing to npm?

**Comment by Gaurav0** [comment]
Done. Did some testing first and added a disclaimer about 'none' causing components to not work.

**Comment by MattMSumner** [comment]
Sweet! Thanks.

**Pull request merged**
